### PR TITLE
pulling in 1.6

### PR DESCRIPTION
**Pull request by mattdjerome**

### CODE REVIEW

**Review by mattdjerome — COMMENTED** [review]
learning pull requests.

**Comment by dan-snelson** [comment]
@mattdjerome:

After a quick skim, you appear to be requesting I merge your organization-specific information.

Please confirm. Thanks.

**Comment by mattdjerome** [comment]
sorry, I'm trying to do the opposite.

**Comment by dan-snelson** [comment]
@mattdjerome:

You appear to be requesting I merge your organization-specific information; closing.

**Pull request closed without merging**
