### PR TITLE
Add additional info fields

### PR DESCRIPTION
**Pull request by drtaru**
I broke the other PR because I am bad at Git

This PR should satisfy #1 & #12 

This adds additional fields to the assetTagCapture screen and as such renames it infoCapture
I also added debug logging for the recon trigger and the infoCapture input if if enabled

### CODE REVIEW

**Review by midiman1000 — COMMENTED** [review]
Hello, and really appreciate the update to this script, I was close on doing it myself, but you did few little things I missed, I'm grateful and learn everyday how to script better and better, thank you.
This is now working as I imagined it would.

**Comment by midiman1000** [comment]
Whoops, I spoke too soon, was testing on a VM, and went to a real Mac and although it's assigning the new info to JAMF, it skipping over all the installations of software.

I think it's to do with this:

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Evaluate User Interaction at Welcome Screen
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

if [[ ${assetTagCapture} == "true" ]]; then

    case ${returncode} in

        0)  ## Process exit code 0 scenario here
            updateScriptLog "WELCOME DIALOG: ${loggedInUser} entered an Asset Tag of ${assetTag} and clicked Continue"
            eval "${dialogSetupYourMacCMD[*]}" & sleep 0.3
            dialogUpdateSetupYourMac "message: Asset Tag reported as \`${assetTag}\`. $message"
            if [[ ${debugMode} == "true" ]]; then
                dialogUpdateSetupYourMac "title: DEBUG MODE | $title"
            fi
            ;;

        2)  ## Process exit code 2 scenario here
            updateScriptLog "WELCOME DIALOG: ${loggedInUser} clicked Quit when prompted to enter Asset Tag"
            exit 0
            ;;

        3)  ## Process exit code 3 scenario here
            updateScriptLog "WELCOME DIALOG: ${loggedInUser} clicked infobutton"
            /usr/bin/osascript -e "set Volume 3"
            /usr/bin/afplay /System/Library/Sounds/Tink.aiff
            ;;

        4)  ## Process exit code 4 scenario here
            updateScriptLog "WELCOME DIALOG: ${loggedInUser} allowed timer to expire"
            eval "${dialogSetupYourMacCMD[*]}" & sleep 0.3
            ;;

        *)  ## Catch all processing
            updateScriptLog "WELCOME DIALOG: Something else happened; Exit code: ${returncode}"
            exit 1
            ;;

    esac

**Comment by drtaru** [comment]
> Whoops, I spoke too soon, was testing on a VM, and went to a real Mac and although it's assigning the new info to JAMF, it skipping over all the installations of software.

Hello, Are you modifying the policy array to match your needs? Can you post the output of the log file that gets written to disk? (you can place logs in between ` marks to create a codeblock)

**Comment by midiman1000** [comment]
Sure give me an hour or so.
Thank you.
Yes,I've adjusted the policy array for my company and it worked perfectly in version 1.2.10 and 1.3.0 with just the asset Tag attribute.

**Comment by midiman1000** [comment]
[com.experianDeployment.log](https://github.com/dan-snelson/dialog-scripts/files/10008341/com.experianDeployment.log)

**Comment by drtaru** [comment]
Your log claims you are having issues installing the following applications which is not a failure of the script but is indicative of issues running the Jamf policy trigger. but it is running triggers.

the triggers that failed are 
• Cisco AnyConnect  
• Microsoft Teams  
• Google Chrome  
• Microsoft Compnay Portal  


You can possibly see what the Jamf failures are by checking `/var/log/jamf.log`

**Comment by dan-snelson** [comment]
Sorry; closed by accident.

**Comment by drtaru** [comment]
Dan I think you need a vacation 🤣

**Comment by dan-snelson** [comment]
Thanks for your speedy work on this, @drtaru.

Here's the rub (and why [Issue No. 1](https://github.com/dan-snelson/dialog-scripts/issues/1) has been opened for so long).

- For [Issue No. 11](https://github.com/dan-snelson/dialog-scripts/issues/11), only the **Welcome** screen is needed (which shouldn't be too difficult)
- For our use-case, we only need **Asset Tag**
- For this issue, the following inputs are required:
  - **Computer Name**
  - **Location**
  - **Department**

Screenshot 2022-11-14 at 8 38 17 PM

My personal preference is to provide a turn-key solution where Parameter `5` would be **any** combination of …
- `welcome`
- `asset tag`
- `computer name`
- `location`
- `department`
- `etc`
- `etc`

… which would be dynamically added on-the-fly — including the error-checking code and `recon` logic — so a Jamf Pro admin who doesn't have the cycles to code could just "add water and stir."

However, as previously mentioned, finding the cycles to code this modular approach — of which my employer would gain little to no benefit — is quite challenging.

At your leisure, please share your thoughts and in the meantime, I'll counsel with a few others.

Thanks again.

**Comment by midiman1000** [comment]
> Your log claims you are having issues installing the following applications which is not a failure of the script but is indicative of issues running the Jamf policy trigger. but it is running triggers.
> 
> the triggers that failed are • Cisco AnyConnect • Microsoft Teams • Google Chrome • Microsoft Compnay Portal
> 
> You can possibly see what the Jamf failures are by checking `/var/log/jamf.log`

Thanks for update, how do explain me using 1.2.10 and it installs fine, where's 1.3.0 with the new updates does not.?
Can I let you see what I've done to the code and take for me, I followed all your updates to the "T", but a new set of eyes on it should help. I appreciate all your help on this. The info like computerName, Asset TAG and department are working but it's the next page to install where it's failing in 1.3.0.

**Comment by drtaru** [comment]
@midiman1000 The issue is with your jamf policy scoping I would guess. Having a policy scoped to once per computer and having already run through 1.2.10 could cause something like this.
Have you tried on a freshly wiped machine?

**Comment by midiman1000** [comment]
> Thanks for your speedy work on this, @drtaru.
> 
> Here's the rub (and why [Issue No. 1](https://github.com/dan-snelson/dialog-scripts/issues/1) has been opened for so long).
> 
> * For [Issue No. 11](https://github.com/dan-snelson/dialog-scripts/issues/11), only the **Welcome** screen is needed (which shouldn't be too difficult)
> * For our use-case, we only need **Asset Tag**
> * For this issue, the following inputs are required:
>   
>   * **Computer Name**
>   * **Location**
>   * **Department**
> 
> Screenshot 2022-11-14 at 8 38 17 PM
> 
> My personal preference is to provide a turn-key solution where Parameter `5` would be **any** combination of …
> 
> * `welcome`
> * `asset tag`
> * `computer name`
> * `location`
> * `department`
> * `etc`
> * `etc`
> 
> … which would be dynamically added on-the-fly — including the error-checking code and `recon` logic — so a Jamf Pro admin who doesn't have the cycles to code could just "add water and stir."
> 
> However, as previously mentioned, finding the cycles to code this modular approach — of which my employer would gain little to no benefit — is quite challenging.
> 
> At your leisure, please share your thoughts and in the meantime, I'll counsel with a few others.
> 
> Thanks again.

So are you saying that each attribute "computerName, Asset Tag, department needs to be part of the parameters? Just want to understand your logic here, many thanks for the work, it's appreciated.

**Comment by midiman1000** [comment]
> @midiman1000 The issue is with your jamf policy scoping I would guess. Having a policy scoped to once per computer and having already run through 1.2.10 could cause something like this.
> Have you tried on a freshly wiped machine?
> None of the changes I made should cause this, have you tried running 1.3.0 without my edits to see if you are still having issues, then we can narrow down wether it is my contribution or the core code.

Let me try a basic execution of the 1.3.0, I used a wiped Mac yes, and the scope is set to on-going...I've flushed the scope in the policy and will try again and let you know. Can I share the code with you? Maybe that can narrow it down. Maybe it's me and I missed something.?

**Comment by drtaru** [comment]
@midiman1000 If you are a member of the Mac Admins slack you can DM me direct and that would be better than cluttering this PR. you can find me at the same username @drtaru

**Comment by midiman1000** [comment]
> > @midiman1000 The issue is with your jamf policy scoping I would guess. Having a policy scoped to once per computer and having already run through 1.2.10 could cause something like this.
> > Have you tried on a freshly wiped machine?
> > None of the changes I made should cause this, have you tried running 1.3.0 without my edits to see if you are still having issues, then we can narrow down wether it is my contribution or the core code.
> 
> Let me try a basic execution of the 1.3.0, I used a wiped Mac yes, and the scope is set to on-going...I've flushed the scope in the policy and will try again and let you know. Can I share the code with you? Maybe that can narrow it down. Maybe it's me and I missed something.? It's on-going just for testing.

Ok, so a few itemizations for our company and 1.3.0 with just the asset tag is working now. I'll add the updated details for the other changes you made for more fields and get back to you and yes I'll find you on Slack. Thank you.

**Comment by midiman1000** [comment]
> @midiman1000 If you are a member of the Mac Admins slack you can DM me direct and that would be better than cluttering this PR. you can find me at the same username @drtaru

Yes, I just pinged you there.

**Comment by dan-snelson** [comment]
Thanks for the ongoing discussion, @midiman1000 and @drtaru and sorry for any Dan-induced confusion.

I'm thinking it'd be slick for **Parameter 4** if you could just specify which features you wanted in a space-delimited list and the Welcome screen would be built on-the-fly.

So, one Mac Admin may only need to prompt users for Computer Name and Location:
**Parameter 4:** `computerName location` (presumes Welcome screen)

Another Mac Admin may only need the Welcome screen:
**Parameter 4:** `welcome` (no input fields)

We only need Asset Tag:
**Parameter 4:** `assetTag` (presumes Welcome screen)

Yet another Mac Admin would like to prompt users for their:
- [Assigned User Name](#14)
- Computer name
- Asset Tag
- Department
- Location

**Parameter 4:** `assignedUserName computerName assetTag department location` (presumes Welcome screen)

**Comment by colorenz** [comment]
Quick Idea.... Maybe we can use something like that to show the additional fields.


#fileds="assettag"
fields="no"

if [[ "${fields}" == "assettag" ]]; then
    showAssetag=""
else
    showAssetag="#"
fi

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# "Welcome / Asset Tag" Dialog Settings and Features
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

dialogWelcomeCMD="$dialogApp \
--title \"$welcomeTitle\" \
--message \"$welcomeMessage\" \
--icon \"$welcomeIcon\" \
--iconsize 198 \
--button1text \"Continue\" \
--button2text \"Quit\" \
--button2disabled \
--infotext \"$scriptVersion\" \
--blurscreen \
--ontop \
--titlefont 'size=26' \
--messagefont 'size=16' \
$showAssetag--textfield \"Asset Tag\",required=true,prompt=\"Please enter your Mac's seven-digit Asset Tag\",regex='^(AP|IP)?[0-9]{7,}$',regexerror=\"Please enter (at least) seven digits for the Asset Tag, optionally preceed by either 'AP' or 'IP'. \" \
--quitkey k \
--commandfile \"$welcomeCommandFile\" "

**Comment by dan-snelson** [comment]
@drtaru:

Please allow me to publicly offer you my heartfelt thanks for all your contributions over the past several days.

After much thought and counseling with others, I've decided to go with Bart's JSON approach, which is now available for testing in [v1.3.2 RC1](https://github.com/dan-snelson/dialog-scripts/blob/v1.3.2-rc/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash).

Thank you, thank you, thank you.

**Pull request closed without merging**
