### PR TITLE
Add wait check for mbsetupuser_/root/loginwindow

### PR DESCRIPTION
**Pull request by drtaru**
Added wait check for root/loginwindow/mbsetupuser_ accounts. Untested, needs review.

### CODE REVIEW

**Review by dan-snelson — CHANGES_REQUESTED** [review]
@drtaru:

Thanks for the Pull Request.

I'm not a big fan of infinite `while` loops.

I recommend something along the lines of:

```
while pgrep -q "Setup Assistant" ; do
    echo "Setup Assistant is running; pausing for 10 seconds"
    sleep 10
done

echo "Setup Assistant is no longer running; proceeding …"
```

**Comment by drtaru** [comment]
Hey Dan, I'll need to do some testing to make sure that only checking for "Setup Assistant" works as expected. I'll have some bandwidth for this next week.

**Comment by dan-snelson** [comment]
Thanks, Andrew.

**Comment by dan-snelson** [comment]
Untested, pseudo code:

```
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Validate Setup Assistant has completed
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

while pgrep -q -x "Setup Assistant" ; do
    updateScriptLog "Setup Assistant is running; pausing for 10 seconds"
    sleep 10
done

updateScriptLog "Setup Assistant is no longer running; proceeding …"



# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Confirm Dock is running / user is at Desktop
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

while ! pgrep -q -x "Dock" ; do
    updateScriptLog "Dock is NOT running; pausing for 10 seconds"
    sleep 10
done

updateScriptLog "Dock is running; proceeding …"
```

**Comment by dan-snelson** [comment]
https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/Introduction-to-Setup-Your-Mac.bash#L52-L74

**Comment by dan-snelson** [comment]
@drtaru Please take a look at [1.5.1-rc1](https://github.com/dan-snelson/dialog-scripts/blob/development/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash).

**Comment by dan-snelson** [comment]
Addressed in [`1.5.1`](https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/CHANGELOG.md#151)

**Pull request closed without merging**
